package com.example.backend.dto.response.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;
import lombok.Data;

import java.net.URI;
import java.time.Instant;
import java.util.Map;

/**
 * RFC 7807 Problem Details representation for consistent error responses.
 */
@Data
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetails {

    /**
     * A URI reference that identifies the problem type.
     */
    @Builder.Default
    private URI type = URI.create("about:blank");

    /**
     * A short, human-readable summary of the problem type.
     */
    private String title;

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    private int status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    private String instance;

    /**
     * Timestamp of the error occurrence.
     */
    private Instant timestamp;

    /**
     * Application-specific error code for programmatic error handling.
     */
    private String code;

    /**
     * Additional extension properties, e.g., field validation errors.
     */
    @Builder.Default
    private Map<String, Object> errors = null;
}

