BEGIN;
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'CUSTOMER';
ALTER TABLE users ALTER COLUMN role SET NOT NULL;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
ALTER TABLE users DROP COLUMN IF EXISTS version;
COMMIT;