-- Alter product_embeddings table to use UUID for product_id
-- Step 1: Drop existing indexes and constraints
DROP INDEX IF EXISTS idx_product_embeddings_product_id;

-- Step 2: Delete all existing data (since we need to convert types and regenerate embeddings anyway)
TRUNCATE TABLE product_embeddings;

-- Step 3: Alter the column type
ALTER TABLE product_embeddings 
    ALTER COLUMN product_id TYPE UUID USING product_id::text::uuid;

-- Step 4: Recreate index
CREATE INDEX idx_product_embeddings_product_id ON product_embeddings(product_id);

-- Note: Embeddings will be regenerated by the cron job automatically
